roualdes/bridgestan

julia/MCMC.jl, julia/Project.toml, julia/example.jl, julia/src/BridgeStan.jl, julia/test/Manifest.toml, julia/test/Project.toml, julia/test/runtests.jl, python/test/test_bridgestan.py
=> [Julia] Interface Improvements

.github/workflows/main.yaml, R/bridgestan.R, stan/build_all.ps1
This PR adds CI for the Julia and R client on Windows. Since #12, the Julia client alone should be enough to make sure we don't have any major regressions, but the R client has some Windows-specific things which are good to test as well. 
The Python client seems to have difficulty with the complex environment in the Github Actions runner (I have counted 5+ libgcc installs - _so far_) and fails to load. I think it's probably solvable (I have two separate Windows machines that it does work on), but for now I figured it was better to have some testing rather than wait.
=> Add partial Windows CI

.github/workflows/docs.yaml, .gitignore, CONTRIBUTING.md, julia/docs/Manifest.toml, julia/docs/Project.toml, julia/docs/README.md, julia/docs/make.jl, julia/docs/src/julia.md, julia/src/BridgeStan.jl, python/docs/_static/css/Documenter.css, python/docs/conf.py, python/docs/languages/julia.md, python/docs/languages/julia.rst
This was discussed in the comments of #7.
This uses `DocumenterMarkdown` to build a Markdown version of the Julia docs and embeds it in Sphinx. The output is not quite as pretty as Python's, but I think it's not too bad:
If you don't have Julia installed, I am assuming you're not updating the Julia docs, so it will ignore the error and proceed.
=> Add Julia doc and automated Documenter -> Sphinx pipeline

.github/workflows/main.yaml, .gitignore, Makefile, c-example/Makefile, c-example/README.md, c-example/example.c, python/docs/languages/c-api.rst
Discussed in #21, the refactor into headers lets you call bridged models from pure C. This creates an `c-example/` folder with a minimal example of how to do this and how to compile it.
=> Add example of calling from C

src/model_rng.cpp
Replace call with `lp` and `*val = lp` with direct call to *lp.  This fixes the comment in #23.
=> var* arg in deriv calls

.github/workflows/main.yaml, Makefile, test_models/build_all.ps1, test_models/build_all.sh
This removes `test_models/build_all.sh` and `test_models/build_all.ps1` in favor of simply using a make rule called `test_models` to build all test models. This makes it uniform on all platforms and it allows speedups if you run, e.g. `make test_models -j8`
=> Use a Make rule to build all test models

.github/workflows/main.yaml
We are currently installing Python and cmdstanpy to run the `install_cmdstan` script in our CI. This is exactly the kind of thing `pipx`, which comes pre-installed on the Github runners, is designed to do without the additional steps.
=> Use pipx to simplify build step

test_models/simplex/simplex.stan
The Dirichlet prior used in test_models/simplex/simplex.stan was misspecified, fixed to match dimensions of simplex parameter theta.
=> Fix prior in simplex model

.gitignore, R/R/bridgestan.R, R/man/StanModel.Rd, R/tests/testthat/test-bridgestan.R, julia/docs/src/julia.md, julia/src/BridgeStan.jl, julia/src/model.jl, julia/test/model_tests.jl, python/bridgestan/model.py, python/docs/languages/julia.md, python/docs/languages/r.md, python/test/test_stanmodel.py, src/bridgestan.cpp, src/bridgestan.h, src/bridgestanR.cpp, src/bridgestanR.h, src/model_rng.cpp, src/model_rng.hpp
This is a proposal for #40. It includes the version, stanc flags, and Stan defines all in one monolithic string. It is based on the `info` subcommand of CmdStan models, with some extra information
This is the most useful version for debugging (e.g., if we want to ask the user to give us some information), but probably the least useful format if we want it to be machine readable, which would be better served with separate functions for all of this.
Example output:
```
Stan version: 2.30.0
Stan C++ Defines:
STAN_THREADS=true
STAN_MPI=false
STAN_OPENCL=false
STAN_NO_RANGE_CHECKS=false
STAN_CPP_OPTIMS=false
Stan Compiler Details:
stanc_version = stanc3 v2.30.1
stancflags =
```
=> Add `model_info` function

R/R/bridgestan.R, julia/src/model.jl
See discussions in #36 
I can't figure out if Python exposes a comparable way of testing if a DLL is already loaded or not, so for now this is only in the other two interfaces.
=> Add warning in R and Julia for re-loading DSOs

julia/src/BridgeStan.jl, julia/src/compile.jl, python/bridgestan/compile.py, python/test/test_compile.py
Closes #46. 
Based on the feedback in that issue, it seems better to throw an error if someone tries to use the compilation features without having the paths set, rather than a noisy warning every load. This also goes along with e.g. cmdstanpy/r
=> Compilation: Error on use rather than warning on load

.github/dependabot.yml, .github/workflows/docs.yaml, .github/workflows/main.yaml
Recent workflow runs have had a lot of deprecation warnings, see: https://github.com/roualdes/bridgestan/actions/runs/3322699971
This updates the versions we are using to resolve them and enables GitHub's "dependabot" to check them monthly
=> Update GHA workflows to remove deprecated features

.github/workflows/docs.yaml, .github/workflows/main.yaml, Makefile, c-example/Makefile, src/model_rng.cpp
Now that the release candidates are out (https://github.com/stan-dev/cmdstan/issues/1126) we can start testing against them and making the required changes for the next version.
We shouldn't merge this until 2.31 is officially released (~18th of November).
Changes:
- JSON now lives in stan repository instead of cmdstan. We can now drop cmdstan dependency, if we want, in a separate PR.
- We can avoid an extra copy being made in the gradient calculations
=> Support for Stan 2.31

R/R/bridgestan.R, R/tests/testthat/test_collisions.c, c-example/example.c, docs/languages/julia.md, julia/src/BridgeStan.jl, julia/src/compile.jl, julia/src/model.jl, python/bridgestan/model.py, python/example.py, src/bridgestan.cpp, src/bridgestan.h, src/bridgestanR.cpp, src/bridgestanR.h, src/model_rng.cpp, src/model_rng.hpp
Closes #53.
This is a breaking change for the C API, but not for any of the higher level APIs.
=> Prefix any C-exposed symbols with `bs_`

.github/dependabot.yml, .github/workflows/docs.yaml, .github/workflows/main.yaml, .gitignore, .gitmodules, CONTRIBUTING.md, Makefile, README.md, c-example/Makefile, docs/install.rst, docs/languages/julia.md, docs/languages/python.rst, julia/docs/src/julia.md, julia/src/BridgeStan.jl, julia/src/compile.jl, julia/test/compile_tests.jl, julia/test/model_tests.jl, python/bridgestan/__init__.py, python/bridgestan/compile.py, python/test/test_compile.py
This removes the dependency on CmdStan. 
BridgeStan now ships with a copy of the Stan repository, and is able to download `stanc` by the same method CmdStan does.
As part of this we need to pick a "blessed" version of Stan to package with BridgeStan. I have picked Stan 2.31.0 for this as it is the latest version, and I imagine we will want to track this as we go along. 
I have also writen up some documentation on how to use custom versions of Stan and Stanc with bridgestan in the installation instructions.
=> Remove CmdStan Dependency

R/R/bridgestan.R, R/man/StanModel.Rd, docs/languages/julia.md, docs/languages/r.md, julia/src/model.jl, python/bridgestan/model.py, python/test/test_stanmodel.py, src/bridgestan.h, src/model_rng.cpp
Closes #59. The `data` argument to construct can now be either a file path (must end in `.json`) **or** a string containing the json directly
=> Allow JSON data as a string

R/DESCRIPTION, docs/getting-started.rst, julia/Project.toml, julia/docs/Manifest.toml, python/setup.cfg, python/test/test_stanmodel.py, src/model_rng.cpp, src/version.hpp
This closes #19 and should be the last PR merged before BridgeStan 1.0.0 is released. 
A draft release is already visible (if you have write access to the repo) on the releases page https://github.com/roualdes/bridgestan/releases.
After this is merged I will add the current state of `main` as a `.tar.gz` file to that release and then we can publish it.
Changes:
- Set versions in each interface to 1.0
- Added text to the getting started page about downloading from the Releases page 
- Added a `version.hpp` based off of Stan's `version.hpp` and included the current BridgeStan version in `model_info`.
=> [Release] Version bumps and doc for 1.0 release

R/R/bridgestan.R, docs/languages/r.md, python/bridgestan/model.py, src/bridgestan.h
There are some occurrences of JSON object in files not directly owned by BridgeStan, so I left those out.
=> change JSON object to JSON string literal for all BridgeStan owned files

julia/src/model.jl
Re Issue #64, duplicate some doc to emphasize that `StanModel` can accept and pass to `compile_model` the arguments to tweak compilation, `make_args`, and Stanc transpilation `stanc_args`.
=> Add Julia doc to emphasize compile_model args in StanModel; re issue #64

.github/workflows/release.yaml, docs/languages/julia.md, docs/languages/python.rst, julia/Project.toml, julia/docs/src/julia.md, julia/test/compile_tests.jl, julia/test/model_tests.jl, julia/test/runtests.jl, julia/test/util_tests.jl, julia/updateArtifacts.jl, python/README.md, python/setup.cfg
This builds on @sethaxen's work in #70 to create a unified release action for the repo. It also updates a few documentation pages in anticipation of the release.
The steps the Action takes are roughly:
1. Replace the version numbers in all interfaces with the new version
2. Build the `.tar.gz` file we attach to a release
3. Update the Julia `Artifacts.toml` file
4. Push a commit to the repo with the above changes
5. Create a tag and release
6. Push to PyPI (@roualdes this will require us adding a Secret to the repository for a PyPI token once)
7. Comment on the commit from `4` with a `@JuliaRegistrator register`  (@roualdes this will require following the pre-registration instructions here https://github.com/JuliaRegistries/Registrator.jl once)
If any step up to and including 5 fails, you …
=> Add unified release action

src/model_rng.cpp
From the [Math Library documentation](https://mc-stan.org/math/structstan_1_1math_1_1_autodiff_stack_singleton.html):
> Whenever STAN_THREADS is defined then all created child threads must instantiate a [AutodiffStackSingleton](https://mc-stan.org/math/structstan_1_1math_1_1_autodiff_stack_singleton.html) object within the child thread before accessing the AD system in order to initialize the TLS AD tape within the child thread.
We have been creating a `thread_local` AD stack even when `STAN_THREADS` is not defined. This is unnecessary, and probably incurs some extra overhead.
=> Do not create ChainableStacks except when threading

R/example.R
The instructions at https://roualdes.github.io/bridgestan/languages/r.html#example-program are incomplete. This adds the missing instructions necessary to run the example without errors. I added them as comments in example.R but it could also just go in the text in the markdown file.
=> example.R: add missing instructions

.github/workflows/main.yaml, Makefile, c-example/Makefile, test_models/ode/ode.stan
Reported by @modichirag, models which use ODE integrators from Sundials currently fail during the link step. This is because the static libraries in the Math library were not built with `-fPIC`.
This PR:
1. Globally sets -fPIC in CXXFLAGS
2. Cleans up the makefile a bit to remove unnecessary variables
3. Adds a test model from the Stan User's Guide which will be built in CI
=> Make sure -fPIC is set globally so Sundials can link

.github/workflows/main.yaml, Makefile
Follow on to #81, the ode model wasn’t actually being built in our CI runs (oops!)
=> Update list of test models in Makefile

README.md
This adds the following badges to the README (discussed https://github.com/roualdes/bridgestan/pull/86#issuecomment-1479613076):
[![DOCS](https://img.shields.io/badge/docs-latest-blue)](https://roualdes.github.io/bridgestan/) [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.7760173.svg)](https://doi.org/10.5281/zenodo.7760173) [![CI](https://github.com/roualdes/bridgestan/actions/workflows/main.yaml/badge.svg)](https://github.com/roualdes/bridgestan/actions/workflows/main.yaml)
If we wanted to really go maximalist there are also commonly used badges for licenses, pypi downloads, etc. I don't believe Julia has any for their registry.
=> Add README badges for docs, DOI, build status

src/bridgestan.cpp, src/bridgestan.h, src/model_rng.cpp, src/model_rng.hpp
As pointed out by @aseyboldt in #88, our C headers could have many more things marked as `const` than they currently did. This fixes that and cleans up some argument names, also per his suggestion.
=> Fix: Const correctness in C api

src/model_rng.cpp
Partially addresses #93.
Currently, all Stan print statements were redirected to stderr, this changes to stdout while we explore other options.
=> Send Stan outputs to stdout rather than stderr

docs/getting-started.rst
See #96 for a good example of where they are not faster
=> Update section on AD Hessians to clarify they may not be faster

R/R/bridgestan.R, c-example/example.c, julia/src/model.jl, python/bridgestan/__version.py, python/bridgestan/model.py, src/bridgestan.cpp, src/bridgestan.h, src/bridgestanR.cpp, src/bridgestanR.h
Mentioned by @aseyboldt in #95. This adds three declarations to `bridgestan.h`:
```C
extern int bs_major_version;
extern int bs_minor_version;
extern int bs_patch_version;
```
Which are populated by the version number macros we already have in version.hpp. Previously, these versions were only available by pulling apart the string returned by `bs_model_info()`.
This also adds a warning to the Python interface if the model version and python library version differ. This should be rare, but good to check. We can do something similar in Julia in 1.9+ when it is released: [`pkgversion`](https://github.com/JuliaLang/julia/pull/45607)
=> Expose version numbers in C API

c-example/example.c, src/bridgestan.cpp, src/bridgestan.h, src/model_rng.cpp, src/model_rng.hpp
This was requested in #103.
Currently, you can specify a model has no data by passing "". This also allows you to pass `nullptr` for the same thing.
=> Allow nullptr as data argument to constructor

Makefile, README.md, julia/test/model_tests.jl, src/model_rng.cpp
This updates to the newly-released Stan 2.32.0 (see https://github.com/stan-dev/cmdstan/issues/1154)
The only change which are particularly relevant to BridgeStan are the flushing of print statements (see #108) and the changes to `get_dims` and `get_param_names` allowing us to delete a decent chunk of code we don't need
=> Update to Stan 2.32

.github/workflows/main.yaml, docs/conf.py, docs/languages/c-api.rst, src/bridgestan.h
Updates the C API doc to add the typedefs and variables in `bridgestan.h`
=> Add typedefs and variables to C API doc

.github/workflows/docs.yaml, docs/conf.py, docs/languages/julia.md, python/test/test_stanmodel.py
This just fixes one Python test and some of the docs building steps for the release. Everything else for the 2.0.0 release seemed to go smoothly.
=> Tweaks following 2.0 release action

.github/workflows/main.yaml, julia/src/BridgeStan.jl, python/bridgestan/__init__.py, python/test/test_stanmodel.py
This is in response to #117. It isn't a full "fix" (arbitrary user configs could still run into similar problems and need to set their own `%PATH%`s correctly), but it attempts to be a bit friendlier.
This is similar to code in [cmdstanpy](https://github.com/stan-dev/cmdstanpy/blob/cd650840d9b8dec02b98d563bcdf88ccefb10fff/cmdstanpy/model.py#L216-L223). The main difference is (in Python) it also uses [`os.add_dll_directory`](https://docs.python.org/3/library/os.html#os.add_dll_directory). This appears to have fixed the issue which was preventing us from running our Python tests on Windows in Github Actions, so I've re-enabled those.
I'll do a follow on PR which tries to split the Windows CI in to separate jobs per-interface. 
Note: This PR does not change the R interface, since R doesn't …
=> Windows: add TBB (and MinGW DLLs) to load path

.github/workflows/main.yaml
This is based on #118 and should be merged second. Dramatically cleans up our CI action and makes Windows tests more similar to the other platforms.
=> Split Windows CI

R/R/bridgestan.R, R/tests/testthat/test-bridgestan.R
While reading more in the R documentation as part of debugging #131, I noticed this additional flag we should be using (`NAOK = TRUE`):
> Unless formal argument NAOK is true, all the other arguments are checked for missing values NA and for the IEEE special values NaN, Inf and -Inf, and the presence of any of these generates an error. If it is true, these values are passed unchecked. 
NaN/infinity are valid inputs to Stan programs, so we should be allowing them.
=> R: Allow NaN and Inf to be passed in foreign function calls

docs/_static/css/custom.css, docs/conf.py, docs/getting-started.rst, docs/index.rst, docs/internals/documentation.rst, docs/internals/ffi.rst, docs/internals/testing.rst, docs/languages.rst, docs/languages/c-api.rst, docs/languages/python.rst, docs/languages/rust.rst, src/bridgestan.h
This tries to apply a more consistent style to the docs:
- Use more of the [Sphinx directives](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html) for things like files
- Better cross-linking of functions to each other
- I changed the highlight color for `code items` to a shade of green rather than the default pink
- I fixed up some paragraphs which were outdated or missing information
=> Docs: Formatting tweaks and fixes

docs/getting-started.rst, docs/languages/julia.md, docs/languages/python.rst, julia/docs/src/julia.md, julia/example.jl, python/example.py
=> Clarify usage of `set_bridgestan_path` in examples

.github/workflows/main.yaml, Makefile
This fixes CI failures caused by the recent [changes to Github Actions Runners](https://github.com/actions/runner-images/releases/tag/win22%2F20230918.1) to use Mingw 12.2.0
Something like this will hopefully be incorporated into Stan's makefiles in the future.
=> Update CI and Makefile

.github/workflows/release.yaml
A user who was using Windows without administrative permissions reported to me that BridgeStan was failing to install the C++ sources due to a permissions error. 
Some investigating showed that this was due to the symlink in `rust/src`, since [symlinks are always permission 0777](https://man7.org/linux/man-pages/man7/symlink.7.html). After some digging, I found that GNU tar supports replacing symlinks with their targets by passing `-h`/`--dereference`, and in fact [recommends doing this](https://ftp.gnu.org/old-gnu/Manuals/tar-1.12/html_node/tar_115.html):
>  So, for portable archives, do not archive symbolic links as such, and use `--dereference` (`-h`): many systems do not support symbolic links, and moreover, your distribution might be unusable if it contains unresolved symbolic links. …
=> Pass -h/--dereference to tar in release action

.github/workflows/main.yaml, docs/internals/testing.rst, python/bridgestan/model.py, python/pyproject.toml, python/test/test_stanmodel.py
@charlesm93 recently ran into the issue where re-loading the same shared library is a no-op on some systems. 
We warn against this in Julia and R (#45), but in Python the standard library was missing a way to list all already-loaded dlls, so it was left out.
After Charles' prompting, I wrote one: https://github.com/WardBrian/dllist
This small Python package essentially re-implements the same platform-specific logic that the Julia `dllist` function that we use does. I finished it up this morning and put it on PyPI, so if we don't mind a small extra dependency we can add this warning now for Python users as well.
=> Python: Issue warning when re-loading the same module

Makefile, README.md
The Stan submodule has no changes, so this wasn't picked up automatically. The [only changes](https://github.com/stan-dev/stanc3/releases/tag/v2.33.1) in 2.33.1 were in the compiler code generation for tuples.
=> Update stanc to version 2.33.1

src/model_rng.cpp
When I submitted #165 to fix the unnecessary computation in `log_density(propto=True)` I didn't consider that removing the call to `grad` also meant the `var` stack was no longer being cleared, so the memory would build up over time.
You can see this pretty easily in the current version, e.g.:
```python
import numpy as np
import bridgestan
m = bridgestan.StanModel("./test_models/gaussian/gaussian_model.so", "./test_models/gaussian/gaussian.data.json")
def print_lp():
p = np.random.randn(2)
lp = m.log_density(p, propto=True)
print(lp)
for _ in range(100_000):
print_lp()
```
Running this in a repl, you can see that the memory used by the process grows throughout the loop and stays high. After this PR, it does not.
=> Fix memory leak in log_density(propto=True)

CONTRIBUTING.md, Makefile, docs/internals.rst, docs/internals/development.rst, docs/internals/testing.rst, docs/languages/c-api.rst, python/.pylintrc, python/bridgestan/download.py, python/bridgestan/model.py, python/test/test_stanmodel.py
- Cleans up CONTRIBUTING.md to push even more information into the online/rendered documentation
- Improves the makefile error provided when the submodules are missing (similar to https://github.com/stan-dev/cmdstan/pull/1217)
- Added a makefile target to format all code
- Made the `.pylintrc` in `python/` a bit more useful for our project (we still don't enforce this anywhere)
=> Improve developer documentation and experience

.github/workflows/main.yaml, Makefile, docs/conf.py, src/bridgestan.h, src/bridgestanR.h
This PR makes the necessary changes to set the default symbol visibility to "hidden". It's worth reading more about this on the [GCC Wiki](https://gcc.gnu.org/wiki/Visibility).
The summary:
- By default, every symbol in a shared library is available to the linker
- If you are explicit about which symbols _actually should be public_, your compiler can then perform optimizations based on the assumption that the remaining code doesn't need to be accessible
- The Microsoft compilers do this by default, with the added wrinkle of also distinguishing between "public and provided by the current translation unit" (`dllexport`) vs "public and provided by someone else" (`dllimport`)
=> Set up visibility controls for public symbols in the library

README.md
This is just the ones I know about for now. @roualdes feel free to play with wording or add anything you know about!
=> Add README sections on known users of BridgeStan

R/example.R, docs/languages/julia.md, julia/example.jl, julia/src/BridgeStan.jl, julia/src/model.jl, julia/test/compile_tests.jl, python/bridgestan/compile.py, python/bridgestan/model.py, python/bridgestan/util.py, python/example.py, python/test/test_compile.py, python/test/test_stanmodel.py
Closes #187.
Changes:
- Python: `StanModel.from_stan_file` is deprecated. The logic is subsumed in the constructor, which will trigger compilation if the file provided ends in `.stan`
- Python: The `model_data` argument is renamed to `data`. The previous argument still works but issues a warning.
- Python: All functions which accepted strings for file paths now also accept the [`os.PathLike`](https://docs.python.org/3/library/os.html#os.PathLike) interface
- Julia: The `StanModel(;stan_file,...)` overload is deprecated. This logic is now subsumed in the constructor, which will trigger compilation if the file provided ends in `.stan`
=> Unify constructors to always allow a .stan file to be passed

R/R/compile.R, R/R/download.R, python/bridgestan/compile.py, python/bridgestan/download.py, python/bridgestan/model.py
While looking into #190, I found a few small improvements:
- Using `ctypes.byref` is cheaper than actually constructing a `ctypes.pointer` 
- Some missing return type annotations
- A few places where we said 'Bridgestan' instead of 'BridgeStan'
=> Misc. cleanups

docs/internals.rst, docs/internals/details.rst
This is a bit of a weird thing I've been thinking about recently that it is good to alert users for. It's related to #165 and #180.
Basically `propto=True` requires we pass `vars` to Stan. Before #165, we were even calling `grad`, wasting a lot of computation. Since #165, we no longer call grad, but it still may lead to more work than you'd expect, since the Stan math library assumes (justifiably) that if you're calling a function with `var`s you will want gradients, and so it can do some pre-computation for you. Because we never call/use `grad()` in `log_density`, this is wasted effort.
The big offenders are the higher order functions like `reduce_sum`, which basically calculate their entire gradients in the "forward pass".
I wrote up a docs page on implementation details and added a …
=> Add implementation details docs page, note on propto=True for log_density

python/bridgestan/model.py, python/test/test_stanmodel.py
Closes #190
This makes the minimal changes required to accept `ctypes.POINTER(ctypes.c_double)` types alongside numpy arrays for parameter arrays and out parameters
=> Python: allow ctypes pointers for in/out parameters

docs/languages/r.md
Changes `rng_seed` to `seed` in R documentation. 
Searched rest of doc to make sure it didn't appear elsewhere.
Fixes issue #203
=> Update r.md from rng_seed to seed

.github/workflows/main.yaml
The Windows runners [recently updated to PowerShell 7.4](https://github.com/actions/runner-images/issues/9115), which [changed some string quoting behavior](https://stackoverflow.com/a/63627261).
This broke the tests, but because R doesn't really signal its errors in a way Windows likes and https://github.com/actions/runner-images/issues/6668, they stayed green. This fixes them and makes it so we should notice if it happens again.
=> Fix Windows R tests

rust/examples/example.rs
a simple improvement suggestion: a better error message on the Rust example.
e.g.: in case of forgetting to compile the model with `STAN_THREADS=true`.
=> improve panic error message on the Rust example

R/R/bridgestan.R, R/R/compile.R, julia/src/BridgeStan.jl, julia/src/compile.jl, julia/src/model.jl
Unlike Python or R, Julia was setting up the Windows PATH at startup rather than at runtime. Among other things, this meant that calls to `set_bridgestan_path` couldn't influence this, since by the time that function was available, it was already too late.
This is in part thanks to a forum report: https://discourse.mc-stan.org/t/various-compilation-problems-with-various-interfaces/34155/5
=> Move Julia TBB detection to instantiation time

R/README.md, README.md, docs/conf.py, docs/getting-started.rst, docs/internals/development.rst, docs/internals/testing.rst, docs/languages/julia.md, docs/languages/python.rst, docs/languages/r.md, julia/docs/src/julia.md
@avehtari pointed out in #220 that the R documentation never got updated following #172 to mention that the library can now download the sources for you.
This re-writes that second and does a once-over on the other Getting Started text. It is worth us remembering to do this with Rust following #212, as well.
=> Update install doc after R build features

.github/workflows/main.yaml, julia/src/model.jl, julia/test/model_tests.jl, python/bridgestan/model.py, src/bridgestanR.cpp
I recently ran into [some issues](https://github.com/JuliaLang/julia/issues/54257) which originated from improperly passing `bool` arguments as `Int32`s. 
This appears to be fine on most architectures, especially in our case where they're small functions passing arguments on the stack, but it still seemed like something worth fixing up.
I also was made aware of the much more compact `@ccall` Julia macro that makes it much clearer what types are associated with which arguments
=> Clean up our usage of Bool in FFI

.github/workflows/main.yaml, docs/conf.py, docs/languages/julia.md, docs/languages/r.md, julia/docs/src/julia.md, julia/src/compile.jl, julia/src/download.jl, julia/src/model.jl, julia/test/util_tests.jl
Removes a extraneous mention of `Artifacts.jl` after #227, and uses the `@ref` syntax to make Julia functions have clickable links to their "see also" items.
=> Update Julia doc to cross link, remove mention of Artifact

R/R/bridgestan.R, R/R/compile.R, R/man/StanModel.Rd, R/man/StanRNG.Rd, R/man/get_bridgestan_path.Rd, README.md, docs/getting-started.rst, docs/index.rst, docs/languages.rst, docs/languages/julia.md, docs/languages/rust.rst
This is a follow on to #212 with a few extra tweaks to the documentation.
=> Doc: updates following Rust compilation

R/R/bridgestan.R, R/R/compile.R
R has a [maximum length for warnings/error messages,](https://stackoverflow.com/questions/50387667/how-to-prevent-truncation-of-error-messages-in-r) controlled by `options(warning.length)`. This has lead to some confusion before, see [1](https://discourse.mc-stan.org/t/post-hoc-prediction-use-samples-from-fitted-model-in-a-prediction-task/34319/29?u=wardbrian), [2](https://discourse.mc-stan.org/t/various-compilation-problems-with-various-interfaces/34155/7?u=wardbrian)
This adds a check to places where we know there could be long error messages generated by BridgeStan and adds a warning if we know they will be truncated. This warning is reported alongside the error and should help people debug
=> R: Warn if error is too long to print properly

.gitignore, Makefile, docs/getting-started.rst, python/test/test_compile.py, rust/tests/loading.rs, test_models/external/external.stan, test_models/external/make_odds.hpp
This ports the portion of the CmdStan makefile that allows for easier inclusion of external C++ functions:
https://mc-stan.org/docs/cmdstan-guide/external_code.html
Essentially, if the `--allow-undefined` option is passed to stanc3, we then look for a header file to be included during compilation. By default this is `user_header.hpp` in the same folder as the Stan model, but it can be changed by setting `USER_HEADER`.
I'm not sure where is the best place to slot in documentation for this.
=> Support for USER_HEADER in build system

R/DESCRIPTION, R/R/compile.R, R/man/get_bridgestan_path.Rd, R/tests/testthat/test_download.R, docs/languages/julia.md, julia/src/compile.jl, julia/test/util_tests.jl, python/bridgestan/compile.py, python/test/test_download.py
Closes #220 (@avehtari)
This adds a flag `download` to all the interfaces' `get_bridgestan_path` functions. The default is true, which is the previous behavior. Setting to `false` allows you to inspect the current value without triggering a download if it is not found. 
Internally we always use the default value, but some users may want to check if their custom installation is working without triggering a download if it isn't.
=> Add a download flag to get_bridgestan_path

R/R/bridgestan.R, R/tests/testthat/test_model.R, julia/src/model.jl, julia/test/model_tests.jl, python/bridgestan/model.py, python/test/test_stanmodel.py
Would close #239 
I only timed this in Python, where I was not really able to consistently time a difference even in a very simple log density. 
Note: Some existing code will fail after this is merged, even if that code is technically buggy. Worth noting in the release notes.
=> Input size checks

.github/workflows/main.yaml, .gitignore, c-example/Makefile, c-example/README.md, c-example/runtime_loading.c, docs/languages/c-api.rst
Recently a few requests have come in around using BridgeStan from C/C++, but in a way that is more closely aligned with how it is used in the other languages, e.g. providing a path to the library, rather than re-linking your code.
This adds an alternative example that does just that. It also adds some extra config so we can run some of these examples in the Windows CI -- the statically linked one isn't working for me, so I left it out for now still.
=> Add example of loading at runtime from C

.github/workflows/main.yaml, rust/src/bs_safe.rs, src/bridgestan.cpp, src/bridgestan.h
Fixes #258 by explicitly marking the StanLibrary as Send + Sync.
This also adds an entry to the github workflow, which should automatically find most backward incompatible changes that break semver.
=> Fix rust send sync

julia/test/model_tests.jl, src/model_rng.cpp
Closes #272.
This was a simple oversight, similar to the memory leak in #180: `log_density(propto=True)` requires using the autodiff stack, which means we need to take the same precautions as the other log density functions when using it in multiple threads. Namely, at least one `thread_local stan::math::ChainableStack` must have been instantiated on each thread before use. 
This moves the code we had in each function that did this before into one macro, and adds it to the `propto` branch of `log_density()`.
=> Fix log_density calls not being thread safe

src/bridgestan.cpp, src/util.hpp
This removes a lot of boilerplate for our exception handling strategy by using a helper function that takes in a lambda. 
By forcing the function to inline, this actually generates more or less identical assembly: https://godbolt.org/z/3sqWoscnn
In this is too fancy, I understand 😃
=> Maybe: clean up error handling

python/bridgestan/model.py, python/pyproject.toml, python/test/test_stanmodel.py
Requested in https://github.com/roualdes/bridgestan/issues/202#issuecomment-1915032292
This uses the [stanio](https://github.com/stan-dev/stanio) which is a small library also used by CmdStanPy to allow passing of Python dictionaries in the couple places we previously required raw JSON strings
=> Allow passing dictionaries to Python functions using stanio

src/model.hpp, src/util.hpp
This replaces the raw pointer usage inside our model class wrapper with unique pointers. This gets us the correct copy/move semantics automatically and removes the need for a custom destructor (the bs_model class is now a 'rule of zero' class)
I'm using `std::unique_ptr<const char>` instead of `std::string` because the former is still 8 bytes while the later is an implementation defined size, but always at least 24 bytes.  `sizeof(bs_model)` remains unchanged in this PR.
=> Use unique_ptr to simplify model.hpp

julia/test/model_tests.jl, src/model.hpp
I believe this should resolve #289. If you can try it out @nsiccha that would be great!
As discussed in that issue, there are a few functions in stan-math, namely the existing SUNDIALS odes (but also the laplace functions being added soon), that _always_ perform some autodiff, even if they are called with all doubles. 
These functions can appear in `transformed data` or `generated quantities`, two places we were not previously guarding with a `thread_local ChainableStack` instance.
=> Add thread-safe AD chain before calls to write array, constructor
